export const RealtimeEvent = {
  MessageCreated: 'MessageCreated',
  MessageDeleted: 'MessageDeleted',
  UnreadUpdated: 'UnreadUpdated',
  PermissionChanged: 'PermissionChanged',
  NotificationCreated: 'NotificationCreated',
  PresenceChanged: 'PresenceChanged',
  ChannelChanged: 'ChannelChanged',
  MemberJoined: 'MemberJoined',
  MemberChanged: 'MemberChanged',
  VoiceMemberJoined: 'VoiceMemberJoined',
  VoiceMemberLeft: 'VoiceMemberLeft',
  VoiceStateChanged: 'VoiceStateChanged',
  VoiceRouterCapabilities: 'VoiceRouterCapabilities',
  VoiceTransportCreated: 'VoiceTransportCreated',
  VoiceTransportConnect: 'VoiceTransportConnect',
  VoiceProducerCreated: 'VoiceProducerCreated',
  VoiceConsumerCreated: 'VoiceConsumerCreated',
  VoiceConsumerResumed: 'VoiceConsumerResumed',
  VoiceProducerClosed: 'VoiceProducerClosed',
  VoiceActiveSpeaker: 'VoiceActiveSpeaker',
  SyncState: 'SyncState',
} as const;

export type RealtimeEvent = (typeof RealtimeEvent)[keyof typeof RealtimeEvent];
